version: '3'

services:
  mosquitto:
    image: kumarsumit1/mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"
  kafka:
    build: .
    image: kumarsumit1/kafka_ci
    container_name: my_kafka
    hostname: kafkahost
    environment :
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:29092,EXTERNAL://HOSTNAME:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - CONNECT_PLUGIN_PATH=/data
      - CONNECT_KEY_SCHEMA=false
      - CONNECT_VALUE_SCHEMA=false
      - CONNECT_REST_PORT=8083
    volumes:
      - tmp_custom_jars:/data
    expose:
      - "9092"
      - "8083"
      - "9001"
      - "3306"  
    ports :
      - 2181:2181
      - 9092:9092
      - 8083:8083
      - 9001:9001
volumes :
  tmp_custom_jars:
    external: true